### ISSUE TITLE
Arena signs don't work with player permissions

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#15]
If you create arena signs, players are unable to right-click on the signs if they have the `scb.player` permission. OPs can join on the signs, but players are unable to use them.

**Comment by nextinfinity** [comment]
This bug appears to be caused by 3rd party plugins. While I've changed the event priority to potentially override this, it would be beneficial to make sure any other plugins aren't blocking the click from players without a certain bypass permission

**Comment by justwheel** [comment]
Ahh, perhaps WorldGuard then? Should have tested that last night. I will try testing this fix soon!
