### ISSUE TITLE
Make editing arena spawns easier

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#16]
Currently, it is difficult for a server administrator to edit an arena's spawns once they have been set, which can make fixing a bad spawnpoint difficult. This is a double-pronged enhancement suggestion:
### Make spawnpoints temporary visible

By typing a command, it would be convenient for a server administrator to get a visual representation of all the spawnpoints on a map by replacing each spawnpoint with a piece of glass for a duration of about five seconds or so. If this is not feasible at the moment, a list of all spawnpoints with spawnpoint ID numbers and specific coordinates would be fine just as well.
### Make spawnpoints removable

There should also be a way to directly remove spawnpoints after they are created via a command.

**Comment by stevoism** [comment]
Can players spawn in the air? have them spawn like 5/10 blocks above the ground would give them time to get their orientation down before players attack
