### ISSUE TITLE
Force players to respawn or to disconnect

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#17]
After a player dies and is given the option to respawn in their client, there should be a check in place that if a player does not respawn after ten seconds**^1**, they are kicked from the server or sent back to the main lobby for failing to respawn quickly enough. This will prevent players from waiting to respawn after death until the other players have killed each other.

**^1**: Perhaps make this time configurable?

**Comment by justwheel** [comment]
For reference purposes, this plugin is an example of this functionality.

https://www.spigotmc.org/resources/instant-respawn.2884/

**Comment by nextinfinity** [comment]
Never closed this but it was fixed in this commit: https://github.com/nextinfinity/SuperCraftBros/commit/b26a2c710f291c4eb14c9348bc7f791381114e85

**Comment by justwheel** [comment]
@nextinfinity Great, thanks! :+1:
