### ISSUE TITLE
Initial startup throws a minor stacktrace when nothing is created

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#18]
I can't remember what you said about this, but when starting up the plugin for the very first time, [this IllegalArgumentException](http://pastebin.com/TkVaCv1T) is thrown, where Name cannot be null.

**Comment by graywolf336** [comment]
From the stack trace it's happening when the plugin tries to get the lobby's spawn world.

**Comment by justwheel** [comment]
I see. And for clarification purposes, this is still happening with the latest commit, 3ce4bae28ea01dd0364f68428404561c33548c55.

**Comment by justwheel** [comment]
Confirmed fix on my end.
