### ISSUE TITLE
If last player dies and you are falling, you will die on return to main lobby

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#20]
If you are one of two players left in a match and both players are falling into the void, the player who dies last (the winner) will instantly die once they are teleported back to the main lobby from fall damage. There should be a temporary invincibility given to the remaining players once the match ends (or at least adding protection from fall damage to the main lobby as well).

**Comment by stevoism** [comment]
Invulnerability in spawn would be the easiest/ best thing to do IMO

**Comment by justwheel** [comment]
Confirmed fixed.
