### ISSUE TITLE
Implement support for economies

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#21]
I think a major feature addition to SuperCraftBros. would be support for an economy system, either through a unique native system inside of the plugin or support for a third-party economy system, such as Fe or EssentialsEco.

This would be best implemented if a server owner could configure certain payouts for match placements, e.g. first place gets 10 coins, second place gets 5 coins, etc. Then, with said currency, players could purchase new classes to unlock, or perhaps buy access to special arenas. Choices are limitless!

**Comment by stevoism** [comment]
Most of the ones i've played on don't pay unless your first. not saying it has to be said way.

**Comment by nextinfinity** [comment]
In a perfect world, payouts would be customizable by server administrators, which is likely what I'll do.

**Comment by nextinfinity** [comment]
The newest version should add support for giving money to the winner of a match. This is done through Vault so the currency can be used elsewhere, however methods for using currency to unlock classes/maps within SCB have not yet been implemented and a separate issue has been opened to reflect this
