### ISSUE TITLE
Arena signs not properly updating at end of match

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#23]
After a match finishes, sometimes the player counts on a sign will not update. For example, one of my arenas still has 6/8 players inside even though I am the only one on the server. Disabling and re-enabling the arena has no effect.

**Comment by nextinfinity** [comment]
There was a bug where signs weren't saved properly before the plugin disabled, this has been fixed in one of the recent commits.

**Comment by justwheel** [comment]
Awesome, will test this soon!
