### ISSUE TITLE
Add spectator mode?

### ISSUE THREAD

**Issue by Mitty-Chan** [nextinfinity/SuperCraftBros#27]

**Comment by justwheel** [comment]
To elaborate on this, a spectator mode would be the most useful for after a player dies in an arena, so they are teleported back to the game lobby for that match, and they then have the ability to enter spectator mode and watch the match up-close without being seen or getting in the way of other players.

This might be accomplished with setting some kind of provisional Gamemode 3 (i.e. spectator mode) for players via a command or sign. The main issue would be to prevent them from flying outside of the arena and into other maps.

**Comment by stevoism** [comment]
I know this is way late but i just got back on this site, like the PVP is set  up, deny exit, allow exit via tp through world guard would in theory work. Id need to test it with a non staff player to see if it works .

**Comment by nextinfinity** [comment]
Added in https://github.com/nextinfinity/SuperCraftBros/commit/492c81a55f8d52cb36372132783b9793a4f481dc. I ultimately decided against SCB restraining spectators, this will have to be taken care of by servers (most easily by using WorldGuard region flags or by simply placing arenas in individual worlds).
