### ISSUE TITLE
Changing arenas inside of another changes scoreboard, not location

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#30]
If you try to to join another game while already inside of another arena, your scoreboard will change and "set" you into another arena, but you won't actually teleport to the proper arena.

The screenshot shows Arena 2, yet I am inside of Arena 3's match.

![Changing arenas inside of another](http://i.j-f.co/u/879e5af0ef0736b23fe274834d30d9e4.png)

**Comment by ghost** [comment]
I also want to add that it says your in it (scoreboard) but when you move it takes you out.

**Comment by justwheel** [comment]
@Saphiria: You mean when you try moving arenas, like with `/scb join 2` and then doing `/scb join 3` or any physical movement?

**Comment by ghost** [comment]
That's correct.

**Comment by nextinfinity** [comment]
This was fixed with #32
