### ISSUE TITLE
Cannot pass PlayerInteractEvent to SuperCraftBros

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#35]
This was something I originally encountered in v1.3.1, but I wanted to update to v1.3.3 and see if it was still a problem - as of the current commits, this stacktrace is fired on what appears to be every time a player is hit by another player.

[Stacktrace @ Pastebin](http://pastebin.com/raw.php?i=KzjY4sGy)

It's worth noting that this doesn't **appear** to have a direct impact on gameplay among players.

**Comment by nextinfinity** [comment]
This should be solved once the newest version is released.
